sudo: false

language: android

jdk:
  - oraclejdk8
  - openjdk8

android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository

notifications:
  email: false
