sudo: false

language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

notifications:
  email:
    recipients:
      - caipiz@gmail.com
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: always